// vue_sample/src/components/transkey/TranskeyEdit.vue
<template>
    <input :type="type" :id="id" :name="name" :data-tk-kbdtype="keypadType" :data-tk-nextSibling="nextSibling" :placeholder="placeholder" @click="showKeyboard($event.target)"/>
</template>

<script setup>
import {defineProps} from 'vue';

const showKeyboard = (inputObj) => {
    window.tk.onKeyboard(inputObj);
}
defineProps({
    type:String,
    id:String,
    name: String,
    keypadType: String,
    nextSibling: String,
    placeholder: String
})
</script>

// react_sample/src/components/transkey/TranskeyEdit.jsx
import { useEffect, useRef } from "react";
import TranskeyDecodeBtn from "./TranskeyDecodeBtn";
function TranskeyEdit({type, id, name, keypadType, placeholder, isDynamic, isDecodeBtn}){
    const inputRef = useRef(null);
    const decodeTest = (id) => {
        //axios.post()
    }
    useEffect(()=>{
        if(isDynamic!=undefined && isDynamic){
           // debugger;
            tk.setKeyboard(inputRef.current, window.transkey_isMultiCursor, window.tk_useButton, window.tk_useTranskey);
        }
    }, [])
    return (
        <>
            
                <input ref={inputRef} type={type} id={id} name={name} data-tk-kbdtype={keypadType} placeholder={placeholder} data-tk-nextsibling='true' onClick={
                    ()=>{
                        window.tk.onKeyboard(inputRef.current);
                    }
                }/>
                {
                    isDecodeBtn && <TranskeyDecodeBtn id={id}/>
                }
        </>
    )
}

export default TranskeyEdit;
