// react_sample/src/components/mtranskey/MtranskeyEdit.jsx
import { useEffect, useRef } from "react";
import MtranskeyDecodeBtn from "./MtranskeyDecodeBtn";
function MtranskeyEdit({type, id, name, keypadType, keypadBottom, placeholder, isDynamic, isDecodeBtn}){
    const inputRef = useRef(null);
    const decodeTest = (id) => {
        //axios.post()
    }
    useEffect(()=>{
        if(isDynamic!=undefined && isDynamic){
           // debugger;
            mtk.setKeyboard(inputRef.current, window.transkey_isMultiCursor, window.mtk_useButton, window.mtk_useTranskey);
        }
    }, [])
    return (
        <>
            
                <input ref={inputRef} type={type} id={id} name={name} data-tk-kbdtype={keypadType} placeholder={placeholder} data-tk-bottom={keypadBottom} data-tk-nextsibling='true' onClick={
                    ()=>{
                        window.mtk.onKeyboard(inputRef.current);
                    }
                }/>
                {
                    isDecodeBtn && <MtranskeyDecodeBtn id={id}/>
                }
        </>
    )
}

export default MtranskeyEdit;

// vue_sample/src/components/mtranskey/MtranskeyEdit.vue
<template>
    <input :type="type" :id="id" :name="name" :data-tk-kbdtype="keypadType" :data-tk-nextSibling="nextSibling" :placeholder="placeholder" @click="showKeyboard($event.target)"/>
</template>

<script setup>
import {defineProps} from 'vue';

const showKeyboard = (inputObj) => {
    window.mtk.onKeyboard(inputObj);
}
defineProps({
    type:String,
    id:String,
    name: String,
    keypadType: String,
    nextSibling: String,
    placeholder: String
})
</script>
